### ISSUE TITLE
Home Assistant Cast - not working

### ISSUE THREAD

**Issue by jmutnick** [custom-cards/text-divider-row#6]
This element is not working with home assistant cast.  Works fine in a browser and in the mobile app.

Says Custom element doesn't exist: text-divider-row

**Comment by jmutnick** [comment]
@iantrich Do you still support this custom card?

**Comment by iantrich** [comment]
Yeah but I'm not jumping to debug this. Haven't really started using the cast stuff yet.

**Comment by iantrich** [comment]
give this a try: https://gist.github.com/iantrich/7ede7893415e0bef4b42e5a9161d2890

**Comment by jmutnick** [comment]
Still not working.  Rebooted HA and the google home just to cover all bases.

**Comment by iantrich** [comment]
It works for me on a Google home. How do you have this installed?

**Comment by iantrich** [comment]
I have to log out of cast.ha

**Comment by jmutnick** [comment]
Logged out of cast.home-assistant.io and back in, still not working.  I have it installed via HACS.

**Comment by iantrich** [comment]
You have to delete the .gz file to get the cached version to be not used by hacs

**Comment by jmutnick** [comment]
That worked.  Thanks for your patience with me.

**Comment by iantrich** [comment]
Great. Well, not sure why it doesn't like the compiled version, but I'll just put up this as the release for now, I guess. Thanks.
